// Headless smoke test for the browser build: load the Rust `playground.wasm` in
// Node through the very same host bridge the page uses (web/site/host.mjs), run
// programs, and assert their output. Exits non-zero on any mismatch. Run from
// the repo root after building the wasm:
//
//   cargo build -p playground --target wasm32-unknown-unknown --release
//   cp target/wasm32-unknown-unknown/release/playground.wasm web/site/
//   node web/smoke.mjs
//
// This guards the whole browser path: the compiler as wasm, the bundled standard
// library, and the generic `@extern` host bridge, without a browser.

import { readFile } from "node:fs/promises";
import { CELLS } from "./site/cells.mjs";
import { createHost } from "./site/host.mjs";

const host = createHost();
const bytes = await readFile(new URL("./site/playground.wasm", import.meta.url));
const { instance } = await WebAssembly.instantiate(bytes, host.imports);
host.bind(instance.exports);

const isErr = (text) =>
  /error|mismatch|unbound|cannot|fault|unavailable/i.test(text.split("\n")[0]);

// [name, mode, source, expected-substrings]
const CASES = [
  ["hello", 0,
    `@mod MAIN\n\n$ with HOST\n\n$ main : Int =\n\tHOST.print "hi"; 0\n`,
    ["hi"]],
  ["fib", 0,
    `@mod MAIN\n\n$ with STR\n$ with HOST\n\n$ fib : Int -> Int = \\n =\n\tif n ?< 2 => n\n\telse fib (n - 1) + fib (n - 2)\n\n$ main : Int =\n\tHOST.print (STR.from_int (fib 20)); 0\n`,
    ["6765"]],
  ["target reflection", 0,
    `@mod MAIN\n\n$ with HOST\n\n$ main : Int =\n\tHOST.print TARGET.name; 0\n`,
    ["wasm32"]],
  ["emit C", 1,
    `@mod MAIN\n\n$ main : Int = 0\n`,
    ["Generated by the Thrax ccg backend"]],
];

let failures = 0;

for (const [name, mode, src, wants] of CASES) {
  const text = host.compile(src, mode);
  const missing = wants.filter((w) => !text.includes(w));
  if (isErr(text) || missing.length) {
    console.error(`FAIL ${name}: missing ${JSON.stringify(missing)}\n${text}`);
    failures++;
  } else {
    console.log(`ok   ${name}`);
  }
}

// Every tour cell the page ships must compile and run cleanly (some output, no
// diagnostic), so a broken example can never reach the site.
for (const cell of CELLS) {
  const text = host.compile(cell.src, 0);
  if (isErr(text) || text.length === 0) {
    console.error(`FAIL cell:${cell.id}:\n${text}`);
    failures++;
  } else {
    console.log(`ok   cell:${cell.id}`);
  }
}

// The compiler is agnostic about host functions: registering a new one is a pure
// page concern, no rebuild. Prove it by wiring a fresh symbol and calling it.
host.register("shout", (s) => s.toUpperCase());
const shout = host.compile(
  `@mod MAIN\n\n$ echo : Str -> Str = @extern "WASM" "shout" ""\n\n` +
  `$ with HOST\n\n$ main : Int = HOST.print (echo "hi there"); 0\n`,
  0,
);
if (!shout.includes("HI THERE")) {
  console.error(`FAIL register: a registered host function was not reachable\n${shout}`);
  failures++;
} else {
  console.log("ok   register (host function added without a rebuild)");
}

if (failures) {
  console.error(`web/smoke: ${failures} case(s) failed`);
  process.exit(1);
}
console.log("web/smoke: OK -- the browser build runs");
